[common-etcd]
host = "127.0.0.1:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"

[common-redis]
redisAddress = "172.16.122.101:6379"
redisPassword = ""
db = 0